changesDir: .changes
unreleasedDir: unreleased
headerPath: header.tpl.md
versionHeaderPath: ""
versionFooterPath: ""
changelogPath: CHANGELOG.md
versionExt: md
versionFormat: '## {{.Version}} - {{.Time.Format "2006-01-02"}}'
kindFormat: '### {{.Kind}}'
#changeFormat: '* {{.Body}}'
changeFormat: '* [#{{.Custom.Issue}}](https://github.com/pythoninja/easybrake/issues/{{.Custom.Issue}}) {{.Body}}'
headerFormat: ""
footerFormat: ""
kinds:
- label: Added
- label: Changed
- label: Deprecated
- label: Removed
- label: Fixed
- label: Security
custom:
- key: Issue
  type: int
  minInt: 0
